### ISSUE TITLE
Devices List Not Current

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/antifreeze-front-end#14]
There is a particular case wherein the devices aren't current.

Because the JWT isn't deleted when just closing the application (different from logging out), visiting the application again doesn't trigger the login function. This is an issue because getDevices is only called in login. So any devices that are added between the time the app is closed and opened again won't be represented in the list.

**Comment by robrons** [comment]
Thanks for finding this bug. Fixed by calling the initalizeDevice() every time the device page mounts and in order to avoid duplicate devices, I did a simple check to see if the device key is already in the current state.
