### ISSUE TITLE
API Logic

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/antifreeze-front-end#4]
1. Connect to WebSocket
2. Login
3. Send auth request via WS
4. Get devices
    - Reconcile any differences from WS (not MVP)

**Comment by NilsG-S** [comment]
https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
https://github.com/CodeSpaceHQ/telescreen/blob/master/sub-projects/hub/src/common/server/auth.js
https://github.com/CodeSpaceHQ/telescreen/blob/master/sub-projects/hub/src/common/server/oauth-manager.js
https://github.com/NilsG-S/learn-react/blob/master/src/redux/reducers.js
https://github.com/NilsG-S/learn-react/blob/master/src/components/Todos.jsx
https://facebook.github.io/immutable-js/docs/#/OrderedMap

**Comment by robrons** [comment]
Added this functionality.
