### ISSUE TITLE
Route Not Found on Reload

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/antifreeze-front-end#8]
# Solution 1

Webpack-Dev-Server

- https://github.com/reactjs/react-router-tutorial/tree/master/lessons/10-clean-urls

Prod

This, but for Cloud Storage instead of S3.

- https://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html

# Solution 2

- Use Hash Router instead of Browser Router

**Comment by robrons** [comment]
A temporary fix is in place by using: "historyApiFallback: true" in web pack configuration
